services:
  app:
    build: .
    container_name: tshirt-site
    ports:
      - "3019:8000"
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite